eureka:
  client:
    service-url:
      defaultZone: http://snail:123456@euk1.com:7001/eureka/
server:
  port: 82

spring:
  application:
    name: feign-consumer

# feign 使用 hystrix 需手动开启
feign:
  hystrix:
    enabled: true
