eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7001/eureka/
  instance:
    prefer-ip-address: true # 使用ip地址注册
    instance-id: Eureka-provider # 指定服务的id

server:
  port: 81

spring:
  application:
    name: provider

# 不推荐更改这些配置
#续约发送间隔默认30秒，心跳间隔
#eureka.instance.lease-renewal-interval-in-seconds=5
#表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
#eureka.client.registry-fetch-interval-seconds=5
#续约到期时间（默认90秒）
#eureka.instance.lease-expiration-duration-in-seconds=60
