eureka:
  client:
    service-url:
      defaultZone: http://snail:123456@euk1.com:7001/eureka/
    # 开启健康检查，可以实时上报服务的真实健康状态 up/down
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true # 使用ip地址注册
    # instance-id: Eureka-provider # 指定服务的id，服务唯一，不指定默认 主机名:应用名:端口

server:
  port: 82

spring:
  application:
    name: provider

# 不推荐更改这些配置
#续约发送间隔默认30秒，心跳间隔
#eureka.instance.lease-renewal-interval-in-seconds=5
#表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
#eureka.client.registry-fetch-interval-seconds=5
#续约到期时间（默认90秒）
#eureka.instance.lease-expiration-duration-in-seconds=60

# actuator 开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
