eureka:
  client:
    service-url:
      defaultZone: http://snail:123456@euk1.com:7001/eureka/
server:
  port: 91

spring:
  application:
    name: feign-provider
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
  # 链接 springCloud admin 地址
  boot:
    admin:
      client:
        url: http://localhost:8080

# springCloud admin 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always