eureka:
  client:
    # 单节点false，搭建集群true
    # 是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    # 是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
  instance:
    metadata-map:
    # 自定义元数据,可后期用户个性化使用
      snailKey: snailValue
  server:
    # 关闭自我保护机制，一般线上使用开启，超过85%开启
    enable-self-preservation: false
spring:
  profiles:
    active: euk1
  # 应用名称，搭建Server集群，需保证每个节点一致，等同于appName
  application:
    name: EurekaServer

 # springboot security 开启
  security:
    user:
      name: snail
      password: 123456